name: movie_app
description: Movie Application Task
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  dartz: ^0.10.1
  dio: ^5.0.3
  pull_to_refresh: ^2.0.0
  get: ^4.6.5
  flutter_rating_bar: ^4.0.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
